image: Visual Studio 2017

environment:
  matrix:
    - compiler: msvc
      qt: 5.13.2\msvc2017_64

    - compiler: mingw
      qt: 5.13.2\mingw73_64

install:
  # download jom for MSVC build
  - if %compiler% == msvc (
      curl -O -J -L -s -S http://download.qt.io/official_releases/jom/jom.zip
      & 7z x *.zip -oC:\jom > nul
      & del *.zip
    )

before_build:
  - set src_path=%cd%
  - call "C:\Qt\%qt%\bin\qtenv2.bat"
  - if %compiler% == msvc call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if %compiler% == msvc set PATH=C:\jom;%PATH%
  - cd %src_path%

build_script:
  - qmake -config release minutor.pro
  - if %compiler% == msvc jom
  - if %compiler% == mingw mingw32-make -j4

test: off
